name = "phasor-v2"
version = "<%= package.version %>"
description = "Native DEX for Monad"
keywords = ["DEX", "Monad"]

privateSourceCode = false

# Main settings for Factory and Router
[var.main]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
WMON = "0xFb8bf4c1CC7a94c73D209a149eA2AbEa852BC541"
USDC = "0x534b2f3A21130d7a60830c2Df862319e593943A3"

[deploy.UniswapV2Factory]
artifact = "packages/core/contracts/UniswapV2Factory.sol:UniswapV2Factory"
args = ["<%= settings.owner %>"]

[deploy.UniswapV2Router]
artifact = "UniswapV2Router02"
args = ["<%= contracts.UniswapV2Factory.address %>", "<%= settings.WMON %>"]

[deploy.TKN1]
artifact = "packages/core/contracts/test/ERC20.sol:ERC20"
args = [100000000000000]

[deploy.TKN2]
artifact = "packages/core/contracts/test/ERC20.sol:ERC20"
args = [100000000000000]
