name = "phasor-v2-test-tokens"
version = "<%= package.version %>"
description = "Native DEX for Monad"
keywords = ["DEX", "Monad"]

privateSourceCode = false

[deploy.TKN1]
artifact = "packages/core/contracts/test/ERC20.sol:ERC20"
args = ["<%= BigInt(10000000000000000000000000000000) %>"]

[deploy.TKN2]
artifact = "packages/core/contracts/test/ERC20.sol:ERC20"
args = ["<%= BigInt(10000000000000000000000000000000) %>"]

[deploy.WETH9]
artifact = "WETH9"

[deploy.USDT]
artifact = "packages/core/contracts/test/TetherToken.sol:TetherToken"
args = ["<%= BigInt(10000000000000000000000000000000) %>", "Test USD Tether", "USDT", 6]


