name = "phasor-v2-core"
version = "<%= package.version %>"
description = "Native DEX for Monad"
keywords = ["DEX", "Monad"]

privateSourceCode = false

# Main settings for Factory and Router
[var.main]
owner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
WMON = "0x760afe86e5de5fa0ee542fc7b7b713e1c5425701"
USDC = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"

[deploy.UniswapV2Factory]
artifact = "UniswapV2Factory"
args = ["<%= settings.owner %>"]
